version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "legendary-dragons-connection-event-bus"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-he0au9dk38to"
s3_prefix = "legendary-dragons-connection-event-bus"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
