version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "legendary-dragons-card"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-he0au9dk38to"
s3_prefix = "legendary-dragons-card"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LegDragonsWebSocketApi=\"legendary-dragons-ws-api-gateway-LegDragonsWebSocketApi\""
image_repositories = []
