AWSTemplateFormatVersion: 2010-09-09

Description: SAM Template for the legendary dragons front-end

Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: legendary-dragons-frontend
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html

  BucketCloudFormationPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}"
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref AppBucket
                - /*

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access identity between CloudFront and S3 bucket

  AppDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub ${AppBucket}.s3.amazonaws.com
            Id: legendary-dragons-origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
        Enabled: 'true'
        Comment: CloudFront distribution for legendary dragons
        CustomErrorResponses:
          - ErrorCachingMinTTL: 5
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 5
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - OPTIONS
            - GET
            - POST
            - PATCH
            - PUT
            - DELETE
          Compress: 'true'
          TargetOriginId: legendary-dragons-origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'

Outputs:
  DistributionId:
    Value: !Ref AppDistribution
    Description: CloudFront DistributionId
  CloudFrontURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - AppDistribution
          - DomainName
    Description: URL for legendary dragons
